# 名前の定義。このCIジョブの名前を「Rails CI」としています。
name: Rails CI

# このCIジョブが実行されるトリガーを定義。
on:
  push:  # ブランチにプッシュされたときの動作を定義。
    branches:  # 以下のブランチにプッシュされた場合にCIジョブを実行。
      - stn_v1
  pull_request:  # プルリクエストが作成されたときの動作を定義。
    branches:  # 以下のブランチをターゲットとするプルリクエストでCIジョブを実行。
      - stn_v1

# 実行するジョブのリストを定義。
jobs:
  # rubocopジョブの定義。コードのスタイルチェックを行います。
  rubocop:
    runs-on: ubuntu-latest  # 実行環境として最新のUbuntuを使用。
    steps:  # このジョブで実行するステップのリスト。
      - name: Checkout code  # ソースコードをチェックアウトする。
        uses: actions/checkout@v2
      - name: Set up Ruby  # Rubyの環境をセットアップ。
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies  # 必要な依存関係をインストール。
        run: |
          gem install bundler
          bundle install
      - name: Run Rubocop  # Rubocopを実行してコードのスタイルチェック。
        run: bundle exec rubocop

  # RSpecジョブの定義。テストの実行を行います。
  rspec:
    runs-on: ubuntu-latest
    env:  # 環境変数を定義。データベースへの接続情報など。
      DB_USERNAME: postgres
      DB_PASSWORD: shine_stn_app_pass
      DB_HOST: localhost
    services:  # PostgreSQLのサービスを定義。テスト実行時に使用します。
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shine_stn_app_pass
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up database configuration  # データベースの設定ファイルをコピー。
        run: cp config/database.yml.sample config/database.yml
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Setup test database  # テスト用のデータベースをセットアップ。
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Run RSpec  # RSpecを実行してテストを行う。
        run: bundle exec rspec

  # brakemanジョブの定義。セキュリティの脆弱性チェックを行います。
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Brakeman  # Brakemanを実行してセキュリティチェック。
        run: bundle exec brakeman
